[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "pgfspp"
version = "0.1.0"
description = "PGFS++: molecular improvement ensuring synthetic accessibility under diversity constraints"
requires-python = ">=3.10"
dependencies = [
  "numpy",
  "pandas",
  "matplotlib",
  "pyyaml",
  "rdkit",
  "torch",
  "wandb",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]
